# Generated by Django 6.0.2 on 2026-04-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamehistory',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
